name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      node_version: 16.x
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.NODE_VERSION }}
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Unit testing
        run: npm run test

      - name: Build
        run: npm run build
